# Generated by Django 4.2.1 on 2023-09-22 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=32, unique=True)),
                ('start_date', models.DateTimeField(default=None)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('project_owner', models.CharField(default=None, max_length=100, null=True)),
            ],
        ),
    ]
