# Generated by Django 4.2.1 on 2023-09-23 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_app', '0002_sprint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('B', 'bug'), ('T', 'type')], max_length=20)),
                ('status', models.CharField(choices=[('O', 'open'), ('C', 'close')], max_length=20)),
                ('assignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sprint', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_app.sprint')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
