# Generated by Django 4.2.1 on 2023-09-24 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0002_issue_watcher_userprojectrelation_sprint_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('label', models.CharField(max_length=200)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_app.issue')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
