# Generated by Django 4.2.1 on 2023-09-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_alter_user_organization_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
